# DC schema

# --- !Ups
-- MySQL Script generated by MySQL Workbench
-- 2017년 05월 17일 (수) 오전 12시 22분 47초
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jamioni
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jamioni` ;

-- -----------------------------------------------------
-- Schema jamioni
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jamioni` DEFAULT CHARACTER SET utf8mb4 ;
SHOW WARNINGS;
USE `jamioni` ;

-- -----------------------------------------------------
-- Table `jamioni`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jamioni`.`users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jamioni`.`users` (
  `id` BINARY(16) NOT NULL,
  `login_info` TEXT NULL,
  `email` VARCHAR(255) NULL,
  `class_yr` YEAR NULL,
  `activated` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jamioni`.`departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jamioni`.`departments` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jamioni`.`departments` (
  `id` CHAR(10) NOT NULL,
  `name` VARCHAR(45) NULL,
  `campus` TINYINT NULL,
  `affiliation` VARCHAR(10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jamioni`.`departments_with_time`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jamioni`.`departments_with_time` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jamioni`.`departments_with_time` (
  `year` YEAR NOT NULL,
  `semester` TINYINT NOT NULL,
  `department_id` CHAR(10) NOT NULL,
  PRIMARY KEY (`year`, `semester`, `department_id`),
  INDEX `fk_department_time_department1_idx` (`department_id` ASC),
  CONSTRAINT `fk_department_time_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `jamioni`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jamioni`.`subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jamioni`.`subjects` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jamioni`.`subjects` (
  `id` BINARY(16) NOT NULL,
  `code` CHAR(7) NOT NULL,
  `department_id` CHAR(10) NOT NULL,
  `name` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subject_department1_idx` (`department_id` ASC),
  CONSTRAINT `fk_subject_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `jamioni`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jamioni`.`professors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jamioni`.`professors` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jamioni`.`professors` (
  `id` BINARY(16) NOT NULL,
  `name1` TEXT NULL,
  `name2` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jamioni`.`course_areas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jamioni`.`course_areas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jamioni`.`course_areas` (
  `id` BINARY(16) NOT NULL,
  `value` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jamioni`.`course_times`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jamioni`.`course_times` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jamioni`.`course_times` (
  `id` BINARY(16) NOT NULL,
  `time_mon` INT NULL,
  `time_tue` INT NULL,
  `time_wed` INT NULL,
  `time_thu` INT NULL,
  `time_fri` INT NULL,
  `time_sat` INT NULL,
  `time_sun` INT NULL,
  `room_mon` VARCHAR(20) NULL,
  `room_tue` VARCHAR(45) NULL,
  `room_wed` VARCHAR(45) NULL,
  `room_thu` VARCHAR(45) NULL,
  `room_fri` VARCHAR(45) NULL,
  `room_sat` VARCHAR(45) NULL,
  `room_sun` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jamioni`.`courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jamioni`.`courses` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jamioni`.`courses` (
  `id` BINARY(16) NOT NULL,
  `code_prefix` CHAR(7) NOT NULL,
  `code_suffix` TEXT NULL,
  `department_time_year` YEAR NOT NULL,
  `department_time_semester` TINYINT NOT NULL,
  `department_id` CHAR(10) NOT NULL,
  `subjects_id` BINARY(16) NOT NULL,
  `professors_id` BINARY(16) NOT NULL,
  `course_areas_id` BINARY(16) NOT NULL,
  `course_times_id` BINARY(16) NULL,
  `type` VARCHAR(20) NULL,
  `name_1` VARCHAR(45) NULL,
  `name_2` VARCHAR(45) NULL,
  `credit_hours` TINYINT NULL,
  `course_hours` TINYINT NULL,
  `attributes` SET('req', 'onl', 'fl', 'tt') NULL COMMENT 'req => required\nonl => online\nfl => foren language\ntt => team teaching',
  INDEX `fk_course_department_time1_idx` (`department_time_year` ASC, `department_time_semester` ASC, `department_id` ASC),
  INDEX `fk_course_subject1_idx` (`subjects_id` ASC),
  INDEX `fk_courses_professors1_idx` (`professors_id` ASC),
  INDEX `fk_courses_course_areas1_idx` (`course_areas_id` ASC),
  INDEX `fk_courses_course_times1_idx` (`course_times_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_course_department_time1`
    FOREIGN KEY (`department_time_year` , `department_time_semester` , `department_id`)
    REFERENCES `jamioni`.`departments_with_time` (`year` , `semester` , `department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_subject1`
    FOREIGN KEY (`subjects_id`)
    REFERENCES `jamioni`.`subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_courses_professors1`
    FOREIGN KEY (`professors_id`)
    REFERENCES `jamioni`.`professors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_courses_course_areas1`
    FOREIGN KEY (`course_areas_id`)
    REFERENCES `jamioni`.`course_areas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_courses_course_times1`
    FOREIGN KEY (`course_times_id`)
    REFERENCES `jamioni`.`course_times` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Attributes: From the rightmost bit\nRequired\nOnline\nForeignLanguage\nTeamTeaching\n';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jamioni`.`major_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jamioni`.`major_types` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jamioni`.`major_types` (
  `id` BINARY(16) NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jamioni`.`majors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jamioni`.`majors` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jamioni`.`majors` (
  `id` BINARY(16) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `major_type_id` BINARY(16) NOT NULL,
  `year` YEAR NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_major_major_type1_idx` (`major_type_id` ASC),
  CONSTRAINT `fk_major_major_type1`
    FOREIGN KEY (`major_type_id`)
    REFERENCES `jamioni`.`major_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jamioni`.`auth_tokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jamioni`.`auth_tokens` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jamioni`.`auth_tokens` (
  `authtoken_id` BINARY(16) NOT NULL,
  `user_id` BINARY(16) NOT NULL,
  `expiry` DATETIME NULL,
  PRIMARY KEY (`authtoken_id`),
  INDEX `fk_auth_tokens_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_auth_tokens_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jamioni`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jamioni`.`users_has_majors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jamioni`.`users_has_majors` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jamioni`.`users_has_majors` (
  `users_id` BINARY(16) NOT NULL,
  `majors_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`users_id`, `majors_id`),
  INDEX `fk_users_has_majors_majors1_idx` (`majors_id` ASC),
  INDEX `fk_users_has_majors_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_majors_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `jamioni`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_majors_majors1`
    FOREIGN KEY (`majors_id`)
    REFERENCES `jamioni`.`majors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jamioni`.`users_has_courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jamioni`.`users_has_courses` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jamioni`.`users_has_courses` (
  `users_id` BINARY(16) NOT NULL,
  `courses_id` BINARY(16) NOT NULL,
  `retake` TINYINT(1) NULL,
  `future` TINYINT(1) NULL,
  `score` TINYINT NULL COMMENT '-1 -> fail, -2 -> pass\n0 -> F, 2 -> D, 3 -> D+, 4 -> C, 5 -> C+, 6 -> B, 7 -> B+, 8 -> A, 9 -> A+',
  PRIMARY KEY (`users_id`, `courses_id`),
  INDEX `fk_users_has_courses_courses1_idx` (`courses_id` ASC),
  INDEX `fk_users_has_courses_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_courses_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `jamioni`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_courses_courses1`
    FOREIGN KEY (`courses_id`)
    REFERENCES `jamioni`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jamioni`.`majors_has_subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jamioni`.`majors_has_subjects` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jamioni`.`majors_has_subjects` (
  `majors_id` BINARY(16) NOT NULL,
  `subjects_id` BINARY(16) NOT NULL,
  `required` TINYINT(1) NULL,
  PRIMARY KEY (`majors_id`, `subjects_id`),
  INDEX `fk_majors_has_subjects_subjects1_idx` (`subjects_id` ASC),
  INDEX `fk_majors_has_subjects_majors1_idx` (`majors_id` ASC),
  CONSTRAINT `fk_majors_has_subjects_majors1`
    FOREIGN KEY (`majors_id`)
    REFERENCES `jamioni`.`majors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_majors_has_subjects_subjects1`
    FOREIGN KEY (`subjects_id`)
    REFERENCES `jamioni`.`subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
# --- !Downs
DROP SCHEMA IF EXISTS `jamioni`;
