package shared

import scala.collection.immutable.ListMap

object SignUpSettings {
  //TODO Change me!
  val majorList1 = ListMap(
    "AAR01_H1" -> "CORE글로벌지역학 (CORE Global Studies)",
    "A1CE1_H1" -> "EICC학과 (Department of English for International Conferences and Communication)",
    "AAQ01_H1" -> "EU전공 (EU  Major)",
    "AKAA1_H1" -> "Language & Diplomacy전공 (Language & Diplomacy)",
    "AKA_H1" -> "Language & Diplomacy학부 (Division of Language & Diplomacy)",
    "A2AA1_H1" -> "Language & Trade전공 (Language & Trade)",
    "A2A_H1" -> "Language & Trade학부 (Division of Language & Trade)",
    "ALA_H1" -> "경영학부 (Business Administration Division)",
    "ALAA1_H1" -> "경영학전공 (Business Administration)",
    "AEC_H1" -> "경제학부 (Division of Economics)",
    "AECA1_H1" -> "경제학전공 (Economics)",
    "ACDD1_H1" -> "광고·PR·브랜딩전공 (Advertising·Public Relations·Branding)",
    "AFF01_H1" -> "교육학 (Education)",
    "ACAI1_H1" -> "국가리더전공 (National Leader)",
    "AEAA1_H1" -> "국제통상학과 (Department of International  Economics and Law)",
    "AGA_H1" -> "국제학부 (Division of International Studies)",
    "AGAA1_H1" -> "국제학전공 (International Studies)",
    "AAH01_H1" -> "네덜란드어과 (Department of Dutch)",
    "AAD01_H1" -> "노어과 (Department of Russian)",
    "AAC01_H1" -> "독일어과 (Department of German)",
    "AFC01_H1" -> "독일어교육과 (Department of German Education)",
    "ABP01_H1" -> "동북아전공 (North-East Asian Studies Major)",
    "ANJA1_H1" -> "디지털인문한국학전공 (Digital Korean Studies in Humanities)",
    "ABC01_H1" -> "말레이.인도네시아어과 (Department of Malay-Indonesian)",
    "ABJ01_H1" -> "몽골어과 (Department  of Mongolian)",
    "ANDD2_H1" -> "문화콘텐츠학전공 (Cultural Contents Major)",
    "ACD_H1" -> "미디어커뮤니케이션학부 (Division of Media & Communication)",
    "ACDE1_H1" -> "방송·영상·뉴미디어전공 (Broadcasting·Film·New Media)",
    "ADA01_H1" -> "법학과 (Department of Law)",
    "ABF01_H1" -> "베트남어과 (Department of Vietnamese)",
    "AAP01_H1" -> "브릭스전공 (BRICs Major)",
    "ANDB2_H1" -> "사학과 (Department of History)",
    "AKAB1_H1" -> "사회과학전공 (Social Science)",
    "AANA1_H1" -> "세계문화예술경영전공 (Art and Cultural Mediation)",
    "AAI01_H1" -> "스칸디나비아어과 (Department of Scandinavian Languages)",
    "AAE01_H1" -> "스페인어과 (Department of Spanish)",
    "ABD01_H1" -> "아랍어과 (Department of Arabic)",
    "ACDA1_H1" -> "언론·정보전공 (Journalism & Information)",
    "A1CF1_H1" -> "언어와공학전공 (Language and Technology)",
    "ANDC2_H1" -> "언어인지과학과 (Department of Linguistics and Cognitive Science)",
    "A1CD1_H1" -> "영미문학·문화학과 (Department of English Literature and Culture)",
    "AFA01_H1" -> "영어교육과 (Department of English Education)",
    "A1BD1_H1" -> "영어전공 (English Major)",
    "A1CA1_H1" -> "영어학과 (Department of English Linguistics)",
    "AFH01_H1" -> "외국어로서의한국어교육전공 (Teaching Korean as a Foreign Language)",
    "ATMB2_H1" -> "융복합소프트웨어전공 (Software Convergence Major)",
    "AJDA1_H1" -> "융합일본지역전공 (Integrated Japanese Studies)",
    "AJD_H1" -> "융합일본지역학부 (Division of Integrated Japanese Studies)",
    "ABI01_H1" -> "이란어과 (Department of Persian)",
    "AAF01_H1" -> "이탈리아어과 (Department of Italian)",
    "ABG01_H1" -> "인도어과 (Department of Hindi)",
    "AJCA1_H1" -> "일본언어문화전공 (Japanese Language, Literature and Culture)",
    "AJC_H1" -> "일본언어문화학부 (Division of Japanese Language, Literature and Culture)",
    "ACBA1_H1" -> "정치외교학과 (Department of Political Science and Diplomacy)",
    "AFI01_H1" -> "중국어교육과 (Department of Chinese Education)",
    "AICA1_H1" -> "중국언어문화전공 (Chinese Language, Literature and Culture)",
    "AIC_H1" -> "중국언어문화학부 (Division of Chinese Language, Literature and Culture)",
    "AIDA1_H1" -> "중국외교통상전공 (Chinese Foreign Affairs and Commerce)",
    "AID_H1" -> "중국외교통상학부 (Division of Chinese Foreign Affairs and Commerce)",
    "ANDA2_H1" -> "철학과 (Department of Philosophy)",
    "ABE01_H1" -> "태국어과 (Department of Thai)",
    "ABH11_H1" -> "터키.아제르바이잔어과 (Department of Turkish and Azerbaijani)",
    "AAK01_H1" -> "포르투갈어과 (Department of Portuguese)",
    "AAB01_H1" -> "프랑스어과 (Department of French)",
    "AFB01_H1" -> "프랑스어교육과 (Department of French Education)",
    "AAM_H1" -> "프랑스어학부 (Division of French Language)",
    "AFD01_H1" -> "한국어교육과 (Department of Korean Education)",
    "ACBB1_H1" -> "행정학과 (Department of Public Administration)")

  //TODO Change me!
  val majorList2 = ListMap(
    "AAR01_H1" -> "CORE글로벌지역학 (CORE Global Studies)",
    "A1CE1_H1" -> "EICC학과 (Department of English for International Conferences and Communication)",
    "AAQ01_H1" -> "EU전공 (EU  Major)",
    "AKAA1_H1" -> "Language & Diplomacy전공 (Language & Diplomacy)",
    "AKA_H1" -> "Language & Diplomacy학부 (Division of Language & Diplomacy)",
    "A2AA1_H1" -> "Language & Trade전공 (Language & Trade)",
    "A2A_H1" -> "Language & Trade학부 (Division of Language & Trade)",
    "ALA_H1" -> "경영학부 (Business Administration Division)",
    "ALAA1_H1" -> "경영학전공 (Business Administration)",
    "AEC_H1" -> "경제학부 (Division of Economics)",
    "AECA1_H1" -> "경제학전공 (Economics)",
    "ACDD1_H1" -> "광고·PR·브랜딩전공 (Advertising·Public Relations·Branding)",
    "AFF01_H1" -> "교육학 (Education)",
    "ACAI1_H1" -> "국가리더전공 (National Leader)",
    "AEAA1_H1" -> "국제통상학과 (Department of International  Economics and Law)",
    "AGA_H1" -> "국제학부 (Division of International Studies)",
    "AGAA1_H1" -> "국제학전공 (International Studies)",
    "AAH01_H1" -> "네덜란드어과 (Department of Dutch)",
    "AAD01_H1" -> "노어과 (Department of Russian)",
    "AAC01_H1" -> "독일어과 (Department of German)",
    "AFC01_H1" -> "독일어교육과 (Department of German Education)",
    "ABP01_H1" -> "동북아전공 (North-East Asian Studies Major)",
    "ANJA1_H1" -> "디지털인문한국학전공 (Digital Korean Studies in Humanities)",
    "ABC01_H1" -> "말레이.인도네시아어과 (Department of Malay-Indonesian)",
    "ABJ01_H1" -> "몽골어과 (Department  of Mongolian)",
    "ANDD2_H1" -> "문화콘텐츠학전공 (Cultural Contents Major)",
    "ACD_H1" -> "미디어커뮤니케이션학부 (Division of Media & Communication)",
    "ACDE1_H1" -> "방송·영상·뉴미디어전공 (Broadcasting·Film·New Media)",
    "ADA01_H1" -> "법학과 (Department of Law)",
    "ABF01_H1" -> "베트남어과 (Department of Vietnamese)",
    "AAP01_H1" -> "브릭스전공 (BRICs Major)",
    "ANDB2_H1" -> "사학과 (Department of History)",
    "AKAB1_H1" -> "사회과학전공 (Social Science)",
    "AANA1_H1" -> "세계문화예술경영전공 (Art and Cultural Mediation)",
    "AAI01_H1" -> "스칸디나비아어과 (Department of Scandinavian Languages)",
    "AAE01_H1" -> "스페인어과 (Department of Spanish)",
    "ABD01_H1" -> "아랍어과 (Department of Arabic)",
    "ACDA1_H1" -> "언론·정보전공 (Journalism & Information)",
    "A1CF1_H1" -> "언어와공학전공 (Language and Technology)",
    "ANDC2_H1" -> "언어인지과학과 (Department of Linguistics and Cognitive Science)",
    "A1CD1_H1" -> "영미문학·문화학과 (Department of English Literature and Culture)",
    "AFA01_H1" -> "영어교육과 (Department of English Education)",
    "A1BD1_H1" -> "영어전공 (English Major)",
    "A1CA1_H1" -> "영어학과 (Department of English Linguistics)",
    "AFH01_H1" -> "외국어로서의한국어교육전공 (Teaching Korean as a Foreign Language)",
    "ATMB2_H1" -> "융복합소프트웨어전공 (Software Convergence Major)",
    "AJDA1_H1" -> "융합일본지역전공 (Integrated Japanese Studies)",
    "AJD_H1" -> "융합일본지역학부 (Division of Integrated Japanese Studies)",
    "ABI01_H1" -> "이란어과 (Department of Persian)",
    "AAF01_H1" -> "이탈리아어과 (Department of Italian)",
    "ABG01_H1" -> "인도어과 (Department of Hindi)",
    "AJCA1_H1" -> "일본언어문화전공 (Japanese Language, Literature and Culture)",
    "AJC_H1" -> "일본언어문화학부 (Division of Japanese Language, Literature and Culture)",
    "ACBA1_H1" -> "정치외교학과 (Department of Political Science and Diplomacy)",
    "AFI01_H1" -> "중국어교육과 (Department of Chinese Education)",
    "AICA1_H1" -> "중국언어문화전공 (Chinese Language, Literature and Culture)",
    "AIC_H1" -> "중국언어문화학부 (Division of Chinese Language, Literature and Culture)",
    "AIDA1_H1" -> "중국외교통상전공 (Chinese Foreign Affairs and Commerce)",
    "AID_H1" -> "중국외교통상학부 (Division of Chinese Foreign Affairs and Commerce)",
    "ANDA2_H1" -> "철학과 (Department of Philosophy)",
    "ABE01_H1" -> "태국어과 (Department of Thai)",
    "ABH11_H1" -> "터키.아제르바이잔어과 (Department of Turkish and Azerbaijani)",
    "AAK01_H1" -> "포르투갈어과 (Department of Portuguese)",
    "AAB01_H1" -> "프랑스어과 (Department of French)",
    "AFB01_H1" -> "프랑스어교육과 (Department of French Education)",
    "AAM_H1" -> "프랑스어학부 (Division of French Language)",
    "AFD01_H1" -> "한국어교육과 (Department of Korean Education)",
    "ACBB1_H1" -> "행정학과 (Department of Public Administration)")

  //TODO Change me!
  val minorList = ListMap(
    "AAR01_H1" -> "CORE글로벌지역학 (CORE Global Studies)",
    "A1CE1_H1" -> "EICC학과 (Department of English for International Conferences and Communication)",
    "AAQ01_H1" -> "EU전공 (EU  Major)",
    "AKAA1_H1" -> "Language & Diplomacy전공 (Language & Diplomacy)",
    "AKA_H1" -> "Language & Diplomacy학부 (Division of Language & Diplomacy)",
    "A2AA1_H1" -> "Language & Trade전공 (Language & Trade)",
    "A2A_H1" -> "Language & Trade학부 (Division of Language & Trade)",
    "ALA_H1" -> "경영학부 (Business Administration Division)",
    "ALAA1_H1" -> "경영학전공 (Business Administration)",
    "AEC_H1" -> "경제학부 (Division of Economics)",
    "AECA1_H1" -> "경제학전공 (Economics)",
    "ACDD1_H1" -> "광고·PR·브랜딩전공 (Advertising·Public Relations·Branding)",
    "AFF01_H1" -> "교육학 (Education)",
    "ACAI1_H1" -> "국가리더전공 (National Leader)",
    "AEAA1_H1" -> "국제통상학과 (Department of International  Economics and Law)",
    "AGA_H1" -> "국제학부 (Division of International Studies)",
    "AGAA1_H1" -> "국제학전공 (International Studies)",
    "AAH01_H1" -> "네덜란드어과 (Department of Dutch)",
    "AAD01_H1" -> "노어과 (Department of Russian)",
    "AAC01_H1" -> "독일어과 (Department of German)",
    "AFC01_H1" -> "독일어교육과 (Department of German Education)",
    "ABP01_H1" -> "동북아전공 (North-East Asian Studies Major)",
    "ANJA1_H1" -> "디지털인문한국학전공 (Digital Korean Studies in Humanities)",
    "ABC01_H1" -> "말레이.인도네시아어과 (Department of Malay-Indonesian)",
    "ABJ01_H1" -> "몽골어과 (Department  of Mongolian)",
    "ANDD2_H1" -> "문화콘텐츠학전공 (Cultural Contents Major)",
    "ACD_H1" -> "미디어커뮤니케이션학부 (Division of Media & Communication)",
    "ACDE1_H1" -> "방송·영상·뉴미디어전공 (Broadcasting·Film·New Media)",
    "ADA01_H1" -> "법학과 (Department of Law)",
    "ABF01_H1" -> "베트남어과 (Department of Vietnamese)",
    "AAP01_H1" -> "브릭스전공 (BRICs Major)",
    "ANDB2_H1" -> "사학과 (Department of History)",
    "AKAB1_H1" -> "사회과학전공 (Social Science)",
    "AANA1_H1" -> "세계문화예술경영전공 (Art and Cultural Mediation)",
    "AAI01_H1" -> "스칸디나비아어과 (Department of Scandinavian Languages)",
    "AAE01_H1" -> "스페인어과 (Department of Spanish)",
    "ABD01_H1" -> "아랍어과 (Department of Arabic)",
    "ACDA1_H1" -> "언론·정보전공 (Journalism & Information)",
    "A1CF1_H1" -> "언어와공학전공 (Language and Technology)",
    "ANDC2_H1" -> "언어인지과학과 (Department of Linguistics and Cognitive Science)",
    "A1CD1_H1" -> "영미문학·문화학과 (Department of English Literature and Culture)",
    "AFA01_H1" -> "영어교육과 (Department of English Education)",
    "A1BD1_H1" -> "영어전공 (English Major)",
    "A1CA1_H1" -> "영어학과 (Department of English Linguistics)",
    "AFH01_H1" -> "외국어로서의한국어교육전공 (Teaching Korean as a Foreign Language)",
    "ATMB2_H1" -> "융복합소프트웨어전공 (Software Convergence Major)",
    "AJDA1_H1" -> "융합일본지역전공 (Integrated Japanese Studies)",
    "AJD_H1" -> "융합일본지역학부 (Division of Integrated Japanese Studies)",
    "ABI01_H1" -> "이란어과 (Department of Persian)",
    "AAF01_H1" -> "이탈리아어과 (Department of Italian)",
    "ABG01_H1" -> "인도어과 (Department of Hindi)",
    "AJCA1_H1" -> "일본언어문화전공 (Japanese Language, Literature and Culture)",
    "AJC_H1" -> "일본언어문화학부 (Division of Japanese Language, Literature and Culture)",
    "ACBA1_H1" -> "정치외교학과 (Department of Political Science and Diplomacy)",
    "AFI01_H1" -> "중국어교육과 (Department of Chinese Education)",
    "AICA1_H1" -> "중국언어문화전공 (Chinese Language, Literature and Culture)",
    "AIC_H1" -> "중국언어문화학부 (Division of Chinese Language, Literature and Culture)",
    "AIDA1_H1" -> "중국외교통상전공 (Chinese Foreign Affairs and Commerce)",
    "AID_H1" -> "중국외교통상학부 (Division of Chinese Foreign Affairs and Commerce)",
    "ANDA2_H1" -> "철학과 (Department of Philosophy)",
    "ABE01_H1" -> "태국어과 (Department of Thai)",
    "ABH11_H1" -> "터키.아제르바이잔어과 (Department of Turkish and Azerbaijani)",
    "AAK01_H1" -> "포르투갈어과 (Department of Portuguese)",
    "AAB01_H1" -> "프랑스어과 (Department of French)",
    "AFB01_H1" -> "프랑스어교육과 (Department of French Education)",
    "AAM_H1" -> "프랑스어학부 (Division of French Language)",
    "AFD01_H1" -> "한국어교육과 (Department of Korean Education)",
    "ACBB1_H1" -> "행정학과 (Department of Public Administration)")
}
